[package]
edition = "2018"
name = "ra_project_model"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
log = "0.4.8"
rustc-hash = "1.1.0"

cargo_metadata = "0.10.0"

ra_arena = { path = "../ra_arena" }
ra_cfg = { path = "../ra_cfg" }
ra_db = { path = "../ra_db" }
ra_toolchain = { path = "../ra_toolchain" }
ra_proc_macro =  { path = "../ra_proc_macro" }
paths =  { path = "../paths" }
stdx =  { path = "../stdx" }

serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.48"

anyhow = "1.0.26"
