[package]
edition = "2018"
name = "ra_mbe"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
ra_syntax = { path = "../ra_syntax" }
ra_parser = { path = "../ra_parser" }
tt = { path = "../ra_tt", package = "ra_tt" }
rustc-hash = "1.1.0"
smallvec = "1.2.0"
log = "0.4.8"

[dev-dependencies]
test_utils = { path = "../test_utils" }
