[package]
edition = "2018"
name = "ra_syntax"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"
description = "Comment and whitespace preserving parser for the Rust language"
repository = "https://github.com/rust-analyzer/rust-analyzer"

[lib]
doctest = false

[dependencies]
itertools = "0.9.0"
rowan = "0.10.0"
rustc_lexer = { version = "669.0.0", package = "rustc-ap-rustc_lexer" }
rustc-hash = "1.1.0"
arrayvec = "0.5.1"
once_cell = "1.3.1"

stdx = { path = "../stdx" }

ra_text_edit = { path = "../ra_text_edit" }
ra_parser = { path = "../ra_parser" }

# This crate transitively depends on `smol_str` via `rowan`.
# ideally, `serde` should be enabled by `rust-analyzer`, but we enable it here
# to reduce number of compilations
smol_str = { version = "0.1.15", features = ["serde"] }
serde = { version = "1.0.106", features = ["derive"] }

[dev-dependencies]
test_utils = { path = "../test_utils" }
expect = { path = "../expect" }
walkdir = "2.3.1"
rayon = "1"
